apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qo.fullname" . }}-backend-data
  labels:
    {{- include "qo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pvc.backendData.size }}
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qo.fullname" . }}-postgres-data
  labels:
    {{- include "qo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pvc.postgresData.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qo.fullname" . }}-rabbitmq-data
  labels:
    {{- include "qo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pvc.rabbitmqData.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qo.fullname" . }}-minio-data
  labels:
    {{- include "qo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pvc.minioData.size }}
